##spring.data.mongodb.username=any username
##spring.data.mongodb.password=my password
#spring.application.name=journalApp
#
#spring.data.mongodb.uri=mongodb+srv://chaurasiyaveer05_db_user:Agmi9PdMtFriVWJD@cluster0.nhcviko.mongodb.net/?appName=Cluster0
#spring.data.mongodb.database=journaldb
#
#spring.data.mongodb.auto-index-creation=true

